### PR TITLE
Implement a mock server based on the API contract

### PR DESCRIPTION
**Pull request by fwouts**

### CODE REVIEW

**Review by danieltheodosius — COMMENTED** [review]
You might want to include a base url for the server. Current axios client does have a constructor `SpotApi` that takes a config object with `baseUrl` option. Because most contracts do not specify `/api/v2`.

**Comment by fwouts** [comment]
Thanks @danieltheodosius, done. I called this `pathPrefix` instead, as I think `baseUrl` more often refers to the whole base including the domain.

**Review by lfportal — COMMENTED** [review]
Can the mock server be extended to return headers defined in the contract?

**Comment by fwouts** [comment]
@lfportal we don't define response headers at this time :)

**Review by lfportal — APPROVED** [review]

**Pull request merged**
